## 1.Jupyter基本操作

In [11]:
for i in range(10):
    print(x)

100
100
100
100
100
100
100
100
100
100


## 2.三个重要属性

## 3.矩阵创建

In [15]:
import numpy as np
import cv2

In [41]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [18]:
y = np.uint8([1,1,1])
y

array([1, 1, 1], dtype=uint8)

In [19]:
np.float32(x)

array([1., 2., 3.], dtype=float32)

In [22]:
## range
np.arange(2, 10, 1.5)

array([2. , 3.5, 5. , 6.5, 8. , 9.5])

In [24]:
np.linspace(0,2*np.pi,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [26]:
np.zeros((2, 4), dtype=np.uint8)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.ones((3, 3), dtype = np.float32)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [30]:
np.random.randint(0, 10, (4, 4))

array([[7, 7, 6, 5],
       [2, 3, 1, 5],
       [0, 0, 3, 2],
       [7, 3, 3, 1]])

## 4.矩阵转换

In [2]:
import numpy as np

In [3]:
A = np.ones((3, 3), dtype = np.uint8)

In [4]:
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [8]:
A.reshape((-1, 9))

array([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [11]:
A.flatten() #复制

array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [12]:
A.ravel() #引用

array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [13]:
B = np.random.randint(0 , 10, (3, 3))
B

array([[2, 1, 5],
       [7, 3, 4],
       [4, 7, 5]])

In [14]:
B.T

array([[2, 7, 4],
       [1, 3, 7],
       [5, 4, 5]])

In [15]:
B.transpose()

array([[2, 7, 4],
       [1, 3, 7],
       [5, 4, 5]])

In [19]:
np.hstack([A, B, A, B])

array([[1, 1, 1, 2, 1, 5, 1, 1, 1, 2, 1, 5],
       [1, 1, 1, 7, 3, 4, 1, 1, 1, 7, 3, 4],
       [1, 1, 1, 4, 7, 5, 1, 1, 1, 4, 7, 5]])

In [20]:
np.vstack([A, B, A])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 1, 5],
       [7, 3, 4],
       [4, 7, 5],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## 5.最大小值,平均值

In [21]:
B

array([[2, 1, 5],
       [7, 3, 4],
       [4, 7, 5]])

In [22]:
B.max()

7

In [24]:
B.min(), B.mean()

(1, 4.222222222222222)

In [25]:
np.max(B), np.min(B), np.mean(B)

(7, 1, 4.222222222222222)

In [27]:
B.max(axis=1)

array([5, 7, 7])

In [28]:
np.max(B, axis=1)

array([5, 7, 7])

## 6.数学运算

In [29]:
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [30]:
B

array([[2, 1, 5],
       [7, 3, 4],
       [4, 7, 5]])

In [31]:
A + B

array([[3, 2, 6],
       [8, 4, 5],
       [5, 8, 6]])

In [34]:
np.power(B, 2)

array([[ 4,  1, 25],
       [49,  9, 16],
       [16, 49, 25]], dtype=int32)

In [35]:
np.power(B, 0.5)

array([[1.41421356, 1.        , 2.23606798],
       [2.64575131, 1.73205081, 2.        ],
       [2.        , 2.64575131, 2.23606798]])

In [36]:
np.sqrt(B)

array([[1.41421356, 1.        , 2.23606798],
       [2.64575131, 1.73205081, 2.        ],
       [2.        , 2.64575131, 2.23606798]])

In [38]:
np.log10(B+1) #默认e

array([[0.47712125, 0.30103   , 0.77815125],
       [0.90308999, 0.60205999, 0.69897   ],
       [0.69897   , 0.90308999, 0.77815125]])

In [39]:
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [42]:
x

array([1, 2, 3])

In [43]:
A * x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [44]:
A @ x

array([6, 6, 6])

In [45]:
A.dot(x)

array([6, 6, 6])

In [47]:
B

array([[2, 1, 5],
       [7, 3, 4],
       [4, 7, 5]])

In [48]:
A.dot(B)

array([[13, 11, 14],
       [13, 11, 14],
       [13, 11, 14]])

## 7.元素获取

In [49]:
B

array([[2, 1, 5],
       [7, 3, 4],
       [4, 7, 5]])